import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full min-h-screen max-w-[1200px] flex flex-col justify-between px-4 bg-slate-900 mx-auto'>
          <Navbar />
          {children}
          <Footer/>
        </div>
        </body>
    </html>
  )
}
